#FOR USING MUSIC DATABASE
USE MUSIC_DATABASE;


# QUESTION1:- WHO IS THE SENIOR EMPLOYEE BASED ON THE JOB TITLE?
SELECT TITLE,LAST_NAME,FIRST_NAME
FROM employee
ORDER BY LEVELS DESC
LIMIT 1;

    
#QUESTION2:- WHICH COUNTRY HAVE  THE MOST INVOICE?
SELECT BILLING_COUNTRY, COUNT(*) AS TOTAL_INVOICE
FROM INVOICE
GROUP BY BILLING_COUNTRY
ORDER BY TOTAL_INVOICE DESC;


#QUESTION3:- WHAT ARE TOP 3 VALUES OF TOTAL INVOICE?
SELECT TOTAL
FROM INVOICE
ORDER BY TOTAL DESC
LIMIT 3;


#QUESTION4:- WHICH CITY HAS THE BEST CUSTOMERS?WE WOULD LIKE TO THROW A PROMOTIONAL MUSIC FESTIVAL  IN THE CITY WE MADE THE MOST MONEY
#WRITE A QUERY THAT RETURNS ONE CITY THAT HAS THE HIGHEST  SUM OF INVOICE TOTALS.
#RETURN BOTH THE CITY NAME AND SUM OF ALL INVOICE TOTALS

SELECT BILLING_CITY, ROUND(SUM(TOTAL), 3) AS TOTAL_INVOICE
FROM INVOICE
GROUP BY BILLING_CITY
ORDER BY TOTAL_INVOICE DESC
LIMIT 1;


#QUESTION 5:- WHO IS THE BEST CUSTOMER? THE CUSTOMER WHO HAS SPENT  THE MOST MONEY WILL BE DECLARED THE BEST CUSTOMER.
#WRITE A  QUERY THAT RETURNS  THE PERSON WHO HAS SPENT  THE MOST MONEY.

SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, SUM(I.TOTAL) TOTAL_SPENDING
FROM CUSTOMER C 
JOIN INVOICE I ON C.CUSTOMER_ID = I.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID , C.FIRST_NAME , C.LAST_NAME
ORDER BY TOTAL_INVOICE DESC
LIMIT 1;


#QUESTION 6:- WRITE A QUERY TO RETURN THE EMAIL,FIRST NAME,LAST NAEM AND GENRE OF ALL ROCK MUSIC LISTERNERS.
#RETURN YOUR LIST ORDERED ALPHABETICALLY BY EMAIL STARTING WITH A.

SELECT DISTINCT C.EMAIL, C.FIRST_NAME, C.LAST_NAME
FROM CUSTOMER C
JOIN INVOICE I ON C.CUSTOMER_ID = I.CUSTOMER_ID
JOIN INVOICE_LINE IL ON I.INVOICE_ID = IL.INVOICE_ID
WHERE TRACK_ID IN (SELECT TRACK_ID 
                    FROM TRACK T
                    JOIN GENRE G ON T.GENRE_ID = G.GENRE_ID
                    WHERE G.NAME = 'ROCK')
ORDER BY EMAIL;


#QUESTION 7:- LET'S INVITE THE ARTIST WHO HAVE WRITTEN THE MOST ROCK MUSIC IN OUR DATASET.
#WRITE A QUERY THAT RETURNS THE ARTIST NAME AND TOTAL TRACK COUNT OF THE TOP 10 ROCK BANDS.

SELECT ARTIST.ARTIST_ID, ARTIST.NAME,COUNT(ARTIST.ARTIST_ID) AS NUMBER_OF_SONGS
FROM ARTIST
JOIN ALBUM ON ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
JOIN TRACK ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
JOIN GENRE ON TRACK.GENRE_ID = GENRE.GENRE_ID
WHERE GENRE.NAME = 'ROCK'
GROUP BY ARTIST.ARTIST_ID , ARTIST.NAME
ORDER BY NUMBER_OF_SONGS DESC
LIMIT 10;

#QUESTION 8:- RETURN ALL THE TRACK NAMES THAT HAVE A SONG LENGTH LONGER THAN THE AVERAVE SONG LENGTH.
#RETURN THE  NAME AND MILISECONDS FOR EACH TRACK .ORDER BY SONG LENGTH  WITH THE  LONGEST SONGS LISTED FIRST.

SELECT NAME, MILLISECONDS
FROM TRACK
WHERE MILLISECONDS > (SELECT 
            AVG(MILLISECONDS) AS AVG_TRACK_LENGTH
            FROM TRACK)
ORDER BY MILLISECONDS DESC;


#QUESTION 9:-FIND HOW MUCH AMOUNT SPENT BY EACH CUSTOMER ON ARTISTS? WRITE A QUERY TO RETURN CUSTOMER NAME,ARTIST NAME AND TOTAL SPENT.

WITH BEST_SELLING_ARTIST AS(
SELECT ARTIST.ARTIST_ID ,ARTIST.NAME,
SUM(IL.UNIT_PRICE*IL.QUANTITY) AS TOTAL_SALES
FROM INVOICE_LINE IL
JOIN TRACK ON IL.TRACK_ID=TRACK.TRACK_ID
JOIN ALBUM ON TRACK.ALBUM_ID=ALBUM.ALBUM_ID
JOIN ARTIST ON ALBUM.ARTIST_ID=ARTIST.ARTIST_ID
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 1
)
SELECT C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME,BSA.NAME,
SUM(IL.UNIT_PRICE*IL.QUANTITY) AS AMOUNT_SPENT
FROM INVOICE I  
JOIN CUSTOMER C ON C.CUSTOMER_ID=I.CUSTOMER_ID
JOIN INVOICE_LINE IL ON IL.INVOICE_ID=I.INVOICE_ID
JOIN TRACK T ON  T.TRACK_ID=IL.TRACK_ID
JOIN ALBUM ALB ON ALB.ALBUM_ID=T.ALBUM_ID
JOIN BEST_SELLING_ARTIST BSA ON BSA.ARTIST_ID=ALB.ARTIST_ID
GROUP BY 1,2,3,4
ORDER BY 5 DESC;



#QUESTION 10 :- FIND OUT THE MOST POPULAR MUSIC GENRE FOR EACH COUNTRY.
#DERTERMINE THE MOST POPULAR  GENRE AS THE RGENRE WITH THE HIGHEST AMOUNT  OF THE PURCHASES.

WITH POPULAR_GENRE AS 
(
SELECT COUNT(INVOICE_LINE.QUANTITY) AS PURCHASE, CUSTOMER.COUNTRY, GENRE.NAME, GENRE.GENRE_ID,
ROW_NUMBER() OVER(PARTITION BY CUSTOMER.COUNTRY ORDER BY COUNT(INVOICE_LINE.QUANTITY)DESC) AS ROWNO
FROM INVOICE_LINE 
JOIN INVOICE ON INVOICE.INVOICE_ID=INVOICE_LINE.INVOICE_ID
JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID=INVOICE.CUSTOMER_ID
JOIN TRACK ON TRACK.TRACK_ID=INVOICE_LINE.TRACK_ID
JOIN GENRE ON GENRE.GENRE_ID=TRACK.GENRE_ID
GROUP BY 2,3,4
ORDER BY 2 ASC,1 DESC
)
SELECT * FROM  POPULAR_GENRE WHERE ROWNO <=1;


# QUESTION 11:- WRITE A QUERY THAT DETERMINES THE CUSTOMER THAT HAS SPENT THE MOST ON MUSIC FOR EACH COUNTRY.
# WRITE A QUERY  THAT RETURN THE COUTNRY ALING WITH THE TOP CUSTOMER AND HOW MUCH THEY SPENT.
# FOR COUNTRIES WHERE THE TOP AMOUNT SPENT IS SHARED , PROVIDE ALL CUSTOMERS WHO SPENT THIS AMOUNT.

WITH CUSTOMER_WITH_COUNTRY AS(
          SELECT C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME,BILLING_COUNTRY,SUM(TOTAL) AS TOTAL_SPENDING,
          ROW_NUMBER()OVER(PARTITION BY BILLING_COUNTRY ORDER BY SUM(TOTAL) DESC) AS ROWNO
          FROM INVOICE I
          JOIN CUSTOMER  C ON C.CUSTOMER_ID=I.CUSTOMER_ID
          GROUP BY 1,2,3,4
          ORDER BY 4 ASC,5 DESC)
SELECT * FROM CUSTOMER_WITH_COUNTRY WHERE ROWNO=1;